### ISSUE TITLE
大神可以再优化一下这个脚本吗

### ISSUE THREAD

**Issue by S3CR3T-M3N0N** [JaHIY/pdnsd-china-list#1]
用这个转换出来的列表太长而已只有一行，用编辑器打开会自动换行。
用编辑器根本无法复制到pdnsd.conf里面去。
复制进去就报错，因为格式变了。已经变成行了。
希望大神再优化一下这个换行的问题！
谢谢！

**Comment by JaHIY** [comment]
Fixed.

**Comment by S3CR3T-M3N0N** [comment]
感谢大神～
